import { Link } from "react-router-dom";
import { LucideAlertTriangle } from "lucide-react";
import AnimateIn from "../../components/animations/AnimateIn";
import SEOHead from "../../lib/seo";

const MedicalDisclaimer = () => {
    return (
        <main>
            <SEOHead title="Medical Disclaimer — Travel Medicine Advisory Global" description="Important medical disclaimer: TMAG provides informational health guidance, not medical advice." path="/medical-disclaimer" robots="noindex, follow" />
            <section className="px-8 lg:px-16 pt-20 pb-24 max-w-4xl mx-auto">
                <AnimateIn>
                    <span className="inline-block text-sm text-muted bg-button-secondary font-semibold rounded-xl px-4 py-1.5 mb-6">
                        Legal
                    </span>
                    <h1 className="text-4xl md:text-5xl text-heading font-serif leading-[1.1] mb-4">
                        Medical Disclaimer
                    </h1>
                    <p className="text-sm text-muted mb-12">
                        Last updated: February 2026
                    </p>
                </AnimateIn>

                <AnimateIn type="fade" delay={0.15}>
                {/* Prominent warning */}
                <div className="bg-button-secondary rounded-2xl p-6 md:p-8 mb-12 flex items-start gap-4">
                    <div className="w-10 h-10 rounded-xl bg-dark text-background-primary flex items-center justify-center shrink-0">
                        <LucideAlertTriangle className="w-5 h-5" />
                    </div>
                    <p className="text-sm text-heading leading-relaxed font-medium">
                        TMAG does not provide medical advice. The information
                        generated by this platform is for informational purposes
                        only and is not intended to be a substitute for
                        professional medical advice, diagnosis, or treatment.
                    </p>
                </div>
                </AnimateIn>

                <AnimateIn type="fade" delay={0.15}>
                <div className="space-y-10 text-sm text-body leading-relaxed">
                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            1. Informational Purpose Only
                        </h2>
                        <p>
                            All content generated by TMAG including travel
                            health plans, vaccination recommendations,
                            medication suggestions, risk alerts, and emergency
                            information—is provided for general informational
                            purposes only. This content is derived from publicly
                            available data published by global health
                            authorities including the WHO, CDC, ECDC, and local
                            health ministries.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            2. Not a Substitute for Professional Medical Advice
                        </h2>
                        <p>
                            The information provided by TMAG should not be used
                            as a substitute for the advice of a qualified
                            healthcare provider. Always seek the advice of your
                            physician or other qualified health provider with
                            any questions you may have regarding a medical
                            condition, vaccination, or medication.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            3. System-Generated Content
                        </h2>
                        <p>
                            TMAG uses advanced technology to analyze health
                            data and generate personalized travel health plans.
                            While we strive for accuracy, automated systems can make
                            errors. System-generated content may not account for
                            every individual health circumstance, may
                            occasionally contain inaccuracies, and should always
                            be verified with a healthcare professional.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            4. No Doctor-Patient Relationship
                        </h2>
                        <p>
                            Use of TMAG does not create a doctor-patient
                            relationship between you and TMAG, its founders,
                            employees, or affiliates. TMAG is a technology
                            platform, not a healthcare provider.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            5. Emergency Situations
                        </h2>
                        <p>
                            TMAG is not designed for use in medical emergencies.
                            If you are experiencing a medical emergency, contact
                            your local emergency services immediately. Do not
                            rely on information from TMAG or any online service
                            in an emergency situation.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            6. Data Accuracy and Timeliness
                        </h2>
                        <p>
                            While we make every effort to ensure the data used
                            in plan generation is current and accurate, health
                            conditions and requirements can change rapidly.
                            Travel health information can become outdated
                            between the time a plan is generated and the time
                            of travel. We recommend verifying critical
                            information close to your departure date.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            7. Limitation of Liability
                        </h2>
                        <p>
                            TMAG shall not be held liable for any health
                            outcomes, adverse effects, or damages resulting
                            from reliance on information provided by the
                            platform. By using TMAG, you acknowledge that you
                            use the service at your own risk and agree to hold
                            TMAG harmless from any claims arising from such
                            use.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            8. Pre-Existing Conditions
                        </h2>
                        <p>
                            If you have pre-existing medical conditions, take
                            medications, or have known allergies, it is
                            especially important to consult your doctor before
                            acting on any information provided by TMAG. While
                            our platform attempts to account for these factors, it
                            cannot replace a physician's knowledge of your
                            complete medical history.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            Contact
                        </h2>
                        <p>
                            If you have questions about this disclaimer, contact
                            us at{" "}
                            <a href="mailto:legal@tmag.health" className="text-accent underline">
                                legal@tmag.health
                            </a>
                            . Also see our{" "}
                            <Link to="/terms" className="text-accent underline">
                                Terms of Service
                            </Link>{" "}
                            and{" "}
                            <Link to="/privacy" className="text-accent underline">
                                Privacy Policy
                            </Link>
                            .
                        </p>
                    </section>
                </div>
                </AnimateIn>
            </section>
        </main>
    );
};

export default MedicalDisclaimer;
