import { Link } from "react-router-dom";
import AnimateIn from "../../components/animations/AnimateIn";


const TermsOfService = () => {
    return (
        <main>
            <section className="px-8 lg:px-16 pt-20 pb-24 max-w-4xl mx-auto">
                <AnimateIn>
                    <span className="inline-block text-sm text-muted bg-button-secondary font-semibold rounded-xl px-4 py-1.5 mb-6">
                        Legal
                    </span>
                    <h1 className="text-4xl md:text-5xl text-heading font-serif leading-[1.1] mb-4">
                        Terms of Service
                    </h1>
                    <p className="text-sm text-muted mb-12">
                        Last updated: February 2026
                    </p>
                </AnimateIn>

                <AnimateIn type="fade" delay={0.15}>
                <div className="space-y-10 text-sm text-body leading-relaxed">
                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            1. Acceptance of Terms
                        </h2>
                        <p>
                            By accessing or using TMAG (Travel Medicine Advisory
                            Global), you agree to be bound by these Terms of
                            Service. If you do not agree, do not use the
                            service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            2. Description of Service
                        </h2>
                        <p>
                            TMAG is an AI-powered platform that generates
                            personalized travel health advisory plans based on
                            user-provided information and data from public
                            health authorities. The service is informational
                            only and does not constitute medical advice,
                            diagnosis, or treatment.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            3. Not Medical Advice
                        </h2>
                        <p>
                            TMAG does not provide medical advice. All content
                            generated by the platform is for informational
                            purposes only. You should always consult a
                            qualified healthcare professional before making
                            health-related decisions. See our{" "}
                            <Link to="/medical-disclaimer" className="text-accent underline">
                                Medical Disclaimer
                            </Link>{" "}
                            for full details.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            4. User Accounts
                        </h2>
                        <p>
                            You are responsible for maintaining the
                            confidentiality of your account credentials and for
                            all activity under your account. You must provide
                            accurate information when creating an account and
                            keep it up to date.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            5. Credits and Payment
                        </h2>
                        <p className="mb-2">
                            Credits are used to generate travel health plans.
                            One credit produces one plan. Credits do not expire.
                            The first plan is provided free of charge.
                        </p>
                        <p>
                            Unused credits are refundable within 30 days of
                            purchase. Used credits are non-refundable. Prices
                            are subject to change with 30 days' notice to
                            existing users.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            6. Acceptable Use
                        </h2>
                        <p>
                            You may not use TMAG to: distribute automated
                            queries or scrape content; resell generated plans
                            without authorization; submit false health
                            information; or use the service for any unlawful
                            purpose.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            7. Intellectual Property
                        </h2>
                        <p>
                            All content, design, and technology comprising TMAG
                            are owned by TMAG or its licensors. Generated plans
                            are licensed for your personal or organizational
                            use and may not be redistributed commercially.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            8. Limitation of Liability
                        </h2>
                        <p>
                            TMAG is provided "as is" without warranties of any
                            kind. We are not liable for any health outcomes
                            resulting from use of the service. Our total
                            liability is limited to the amount you paid for the
                            credits in question.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            9. Termination
                        </h2>
                        <p>
                            We may suspend or terminate your access if you
                            violate these terms. You may delete your account at
                            any time. Upon termination, your right to use the
                            service ceases and any unused credits may be
                            refunded per our refund policy.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            10. Changes to Terms
                        </h2>
                        <p>
                            We may update these terms from time to time. We
                            will notify users of material changes via email or
                            in-app notification. Continued use after changes
                            constitutes acceptance.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-lg font-serif text-heading mb-3">
                            Contact
                        </h2>
                        <p>
                            Questions about these terms? Contact us at{" "}
                            <a href="mailto:legal@tmag.health" className="text-accent underline">
                                legal@tmag.health
                            </a>
                            .
                        </p>
                    </section>
                </div>
                </AnimateIn>
            </section>
        </main>
    );
};

export default TermsOfService;
